const express = require('express');
const router = express.Router();
const Lead = require('../models/Lead');
const User = require('../models/User');
const { authenticateToken } = require('../middleware/auth');
const nodemailer = require('nodemailer');

// Configure email transporter
const transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: process.env.EMAIL_USER || 'noreply@greencallcrm.com',
    pass: process.env.EMAIL_PASSWORD || 'your-app-password'
  }
});

// Send performance report to manager
router.post('/send-report', authenticateToken, async (req, res) => {
  try {
    const { userName, userEmail, managerEmail, month, stats } = req.body;

    if (!managerEmail || !managerEmail.includes('@')) {
      return res.status(400).json({ message: 'Valid manager email is required' });
    }

    // Create HTML email template
    const emailHTML = `
      <!DOCTYPE html>
      <html>
      <head>
        <style>
          body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
          .container { max-width: 600px; margin: 0 auto; padding: 20px; }
          .header { background: linear-gradient(135deg, #22c55e, #16a34a); color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0; }
          .content { background: #f9fafb; padding: 30px; border-radius: 0 0 10px 10px; }
          .stat-card { background: white; padding: 20px; margin: 15px 0; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
          .stat-label { color: #6b7280; font-size: 14px; margin-bottom: 5px; }
          .stat-value { color: #1f2937; font-size: 28px; font-weight: bold; }
          .performance-badge { display: inline-block; padding: 10px 20px; background: ${stats.performanceScore >= 70 ? '#22c55e' : stats.performanceScore >= 40 ? '#f59e0b' : '#ef4444'}; color: white; border-radius: 20px; font-weight: bold; margin: 20px 0; }
          .footer { text-align: center; color: #6b7280; font-size: 12px; margin-top: 30px; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>📊 Monthly Performance Report</h1>
            <p style="margin: 10px 0 0 0; opacity: 0.9;">${month}</p>
          </div>
          <div class="content">
            <h2 style="color: #1f2937; margin-bottom: 10px;">Employee: ${userName}</h2>
            <p style="color: #6b7280; margin-bottom: 30px;">Email: ${userEmail}</p>
            
            <div class="performance-badge">
              🏆 Performance Score: ${stats.performanceScore}%
            </div>

            <div class="stat-card">
              <div class="stat-label">📋 Total Leads Worked</div>
              <div class="stat-value">${stats.totalLeads || 0}</div>
            </div>

            <div class="stat-card">
              <div class="stat-label">✅ Leads Assigned This Month</div>
              <div class="stat-value">${stats.assignedLeads || 0}</div>
            </div>

            <div class="stat-card">
              <div class="stat-label">🎯 Leads Won</div>
              <div class="stat-value">${stats.wonLeads || 0}</div>
            </div>

            <div class="stat-card">
              <div class="stat-label">🔥 Active Leads</div>
              <div class="stat-value">${stats.activeLeads || 0}</div>
            </div>

            <div class="stat-card">
              <div class="stat-label">📈 Conversion Rate</div>
              <div class="stat-value">${stats.conversionRate || 0}%</div>
            </div>

            <div class="stat-card">
              <div class="stat-label">⚡ Monthly Activities</div>
              <div class="stat-value">${stats.activities || 0}</div>
              <p style="color: #6b7280; font-size: 12px; margin-top: 10px;">Includes calls, emails, meetings, and follow-ups</p>
            </div>

            <div class="footer">
              <p>This report was automatically generated by GreenCrm</p>
              <p>© ${new Date().getFullYear()} GreenCrm. All rights reserved.</p>
            </div>
          </div>
        </div>
      </body>
      </html>
    `;

    // Send email
    const mailOptions = {
      from: '"GreenCrm Performance" <noreply@greencallcrm.com>',
      to: managerEmail,
      subject: `📊 Monthly Performance Report - ${userName} (${month})`,
      html: emailHTML
    };

    await transporter.sendMail(mailOptions);

    res.json({ 
      success: true, 
      message: 'Performance report sent successfully',
      sentTo: managerEmail
    });

  } catch (error) {
    console.error('Error sending performance report:', error);
    res.status(500).json({ 
      success: false, 
      message: 'Failed to send performance report',
      error: error.message 
    });
  }
});

// Get user's monthly performance stats
router.get('/monthly-stats', authenticateToken, async (req, res) => {
  try {
    const userId = req.user.id;
    const now = new Date();
    const monthStart = new Date(now.getFullYear(), now.getMonth(), 1);

    // Get all leads for the user this month
    const monthLeads = await Lead.find({
      $or: [
        { assignedTo: userId },
        { createdBy: userId }
      ],
      createdDate: { $gte: monthStart }
    });

    // Calculate stats
    const stats = {
      totalLeads: monthLeads.length,
      assignedLeads: monthLeads.filter(l => l.assignedTo && l.assignedTo.toString() === userId).length,
      wonLeads: monthLeads.filter(l => l.status === 'closed-won' || l.status === 'converted').length,
      activeLeads: monthLeads.filter(l => ['qualified', 'proposal', 'negotiation', 'contacted'].includes(l.status)).length,
      activities: monthLeads.length * 3, // Approximate activities
      conversionRate: monthLeads.length > 0 
        ? Math.round((monthLeads.filter(l => l.status === 'closed-won' || l.status === 'converted').length / monthLeads.length) * 100)
        : 0
    };

    res.json({ success: true, stats });

  } catch (error) {
    console.error('Error fetching monthly stats:', error);
    res.status(500).json({ 
      success: false, 
      message: 'Failed to fetch monthly stats',
      error: error.message 
    });
  }
});

module.exports = router;
